### ISSUE TITLE
Is OccBEV really a world model?

### ISSUE THREAD

**Issue by chunk425015** [chaytonmin/Awesome-Papers-World-Models-Autonomous-Driving#1]
I notice you list your own work -- OccBEV in the list. However, a world model must be conditioned on the actions of agents and then predict the future. Thus I do not think OccBEV is a world model.  Such overclaim is disgraceful and might tarnish your reputation. Please focus on research rather than boasting.

**Comment by chaytonmin** [comment]
> I notice you list your own work -- OccBEV in the list. However, a world model must be conditioned on the actions of agents and then predict the future. Thus I do not think OccBEV is a world model. Such overclaim is disgraceful and might tarnish your reputation. Please focus on research rather than boasting.

Next version of occ-bev will include prediction of future occupancy. Thanks. we will delete it.

The world model that everyone understands is different. Predicting a 3D world model is sufficient for many tasks. Although 4D future prediction can deepen our understanding of the surrounding environment, I think it is too absolute to consider future prediction as a necessity for world models.
